[11/May/2016 16:32:47] INFO [django_auth_app.services:21] An error occurred trying to get the profile for the user: 1
